const {chromium}=require('playwright');
const {pathToFileURL}=require('node:url');
const path=require('node:path');
const assert=require('node:assert/strict');

(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE?{executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE}:{})});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  await page.goto(pathToFileURL(path.resolve(__dirname,'../index.html')).href);
  const result=await page.evaluate(async()=>{
   const out=[],wait=()=>new Promise(resolve=>setTimeout(resolve,215));
   const check=(name,value)=>{if(!value)throw Error(name);out.push(name);};
   const click=async selector=>{await wait();const button=document.querySelector(selector);if(!button||button.disabled)throw Error('Unavailable '+selector);button.click();};
   const setup=()=>{closeModal(false);state=freshState();state.sound=false;state.chronicle.completedChapters=[1,2,3,4,5,6];Object.assign(state.chronicle.run,{chapter:6,ch:6,name:'测试玩家',inst:'小提琴',scene:'title7',ending:'c6_he'});save();route('chronicle');};
   check('Source keeps all supplied nodes',CHAPTER_SEVEN.nodes.length===34);
   check('Generated story art remains available',CHAPTER_SEVEN_PAGES.length===448&&CHAPTER_SEVEN.nodes.every(node=>node.pageArt.length>0));
   check('Every reading page maps to art',CHAPTER_SEVEN.nodes.every(node=>{let count=0,dialogue=0;for(const line of node.lines){if(line.who==='narrator'){if(dialogue){count++;dialogue=0;}count++;}else if(++dialogue===2){count++;dialogue=0;}}if(dialogue)count++;return node.pageArt.length===count;}));
   check('Chapter seven replaces Lala with TIM',!JSON.stringify(CHAPTER_SEVEN).includes('垃垃')&&!JSON.stringify(CHAPTER_SEVEN).includes('"lala"')&&JSON.stringify(CHAPTER_SEVEN).includes('"tim"'));
   check('Every page has at most two named speakers',CHAPTER_SEVEN.nodes.every(node=>{const turns=[];for(const line of node.lines){if(turns.at(-1)?.who===line.who)turns.at(-1).text+=' '+line.text;else turns.push({...line});}for(let i=0;i<turns.length;i+=2)if(new Set(turns.slice(i,i+2).map(line=>line.who).filter(who=>who!=='narrator')).size>2)return false;return true;}));
   check('All story links resolve',CHAPTER_SEVEN.nodes.every(node=>node.choices.every(choice=>!choice.next||choice.next==='IF'||CHAPTER_SEVEN.nodes.some(item=>item.id===choice.next))));
   setup();
   const tiles=[...document.querySelectorAll('.cp-chapter-tile')];
   check('Official chapter seven precedes personal stories',tiles.at(-2).textContent.includes('CHAPTER 07')&&tiles.at(-2).textContent.includes('后山丘时代')&&tiles.at(-1).textContent.includes('PERSONAL STORIES'));
   await click('[data-cp-chapter="7"]');
   const openingArt=document.querySelector('.cp-novel-art img').src;
   check('Chapter seven enters supplied opening',state.chronicle.chapterSeven.active&&document.querySelector('.cp-chapter-seven')&&document.querySelectorAll('.cp-dialogue-turn').length===1&&document.querySelector('#cpMain').textContent.includes('你加入哈基米也快一年了')&&!document.querySelector('#cpMain').textContent.includes('从最初的成人兴趣小组开始')&&document.querySelector('.cp-novel-top').textContent.includes('1/17'));
   check('Chapter seven narrator uses the global decorative avatar',document.querySelector('.cp-dialogue-turn .cp-speaker img')?.getAttribute('src')===ASSETS.avatarNarrator&&!document.querySelector('.cp-dialogue-turn .cp-speaker [data-dialogue-card]'));
   await click('[data-cp-action="chapter-seven-page"]');
   check('Consecutive narration advances one source line per page',document.querySelectorAll('.cp-dialogue-turn').length===1&&document.querySelector('#cpMain').textContent.includes('从最初的成人兴趣小组开始')&&!document.querySelector('#cpMain').textContent.includes('你参与了一次次排练'));
   check('Split narration advances to its own illustration',document.querySelector('.cp-novel-art img').src!==openingArt&&document.querySelector('.cp-novel-art img').src.includes('/q_start_p1.webp'));
   for(let step=0;step<4;step++)await click('[data-cp-action="chapter-seven-page"]');
   check('The 山丘酉馆 line displays the dedicated sign image',document.querySelector('#cpMain').textContent.includes('山丘酉馆')&&document.querySelector('.cp-novel-art img').src.includes('/q_start_p2.webp'));
   state.chronicle.chapterSeven.scene='q_event2';state.chronicle.chapterSeven.page=3;state.chronicle.chapterSeven.rev++;renderGlobal();
   check('Qiqi tea-pouring page uses corrected semantic art',document.querySelector('.cp-novel-art img').src.includes('/q_event2_p3_fix.webp'));
   state.chronicle.chapterSeven.scene='q_judge';state.chronicle.chapterSeven.page=0;state.chronicle.chapterSeven.rev++;renderGlobal();
   check('Zhu-absent confrontation uses corrected semantic art',document.querySelector('.cp-novel-art img').src.includes('/q_judge_read1_fix.webp'));
   check('Personal story remains an independent final tile',!state.chronicle.personal.active&&[...document.querySelectorAll('.cp-chapter-tile')].at(-1).textContent.includes('独立故事'));
   state.chronicle.chapterSeven.scene='q_after_show';state.chronicle.chapterSeven.page=6;state.chronicle.chapterSeven.rev++;renderGlobal();
   const zhouTurn=[...document.querySelectorAll('.cp-dialogue-turn')].find(turn=>turn.textContent.includes('周总'));
   check('Zhou uses a non-card NPC avatar',!!zhouTurn?.querySelector('img[src*="zhou-npc-avatar-2026-10.webp"]')&&!zhouTurn.querySelector('[data-dialogue-card]')&&!CARD_DEFS.some(card=>card.id==='zhou'));
   state.chronicle.chapterSeven.scene='q01';state.chronicle.chapterSeven.page=0;state.chronicle.chapterSeven.rev++;renderGlobal();
   check('Bingbing unlocks exactly when her story page is reached',cardOwned('bingbing')&&state.cards.encounters.includes('bingbing'));
   const saved=JSON.stringify(state);state=cleanState(JSON.parse(saved));renderGlobal();
   check('Chapter-seven position and Bingbing unlock survive cleaning',state.chronicle.chapterSeven.scene==='q01'&&cardOwned('bingbing'));
   const before=state.coins,tickets=state.cards.tickets;
   Object.assign(state.chronicle.chapterSeven,{active:true,scene:'q_badloan',page:999,ending:null,rev:state.chronicle.chapterSeven.rev+1});renderGlobal();
   await click('[data-seven-choice="0"]');
   check('Official chapter seven grants its own first completion reward',state.chronicle.chapterSeven.ending==='q_badloan'&&state.economy.claimed['chapter:7']&&state.coins===before+15&&state.cards.tickets===tickets+1);
   const after=state.coins;state.chronicle.chapterSeven.scene='q_expose_bad';state.chronicle.chapterSeven.page=999;state.chronicle.chapterSeven.ending=null;state.chronicle.chapterSeven.rev++;renderGlobal();await click('[data-seven-choice="0"]');
   check('Alternate ending does not repeat chapter reward',state.coins===after&&state.chronicle.chapterSeven.endings.includes('q_expose_bad'));
   const old=freshState();delete old.chronicle.chapterSeven;old.chronicle.version=2;old.economy.claimed['chapter:7']=true;old.chronicle.personal.routes.azhe={scene:'complete',page:0,flags:{},done:{azhe_HE:true},resume:null,resumePage:0,read:['azhe_HE'],ending:'azhe_HE',endings:['azhe_HE'],run:1,duets:0,chatIndex:0,focus:0,score:0,dang:0,previewed:null,reply:'',month:0,aff:{},chatSpent:{},chatContacts:{},chatSeen:{},chatReactions:{},chatMessage:null};
   const migrated=cleanState(old);
   check('Old personal chapter-seven receipt migrates away from official chapter',migrated.economy.claimed['personal:first-ending']&&!migrated.economy.claimed['chapter:7']);
   return out;
  });
  assert.deepEqual(errors,[]);
  console.log(`PASS: ${result.length} chapter-seven checks.`);
 } finally {await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
