const {chromium}=require('playwright');
const {pathToFileURL}=require('node:url');const path=require('node:path');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE?{executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE}:{})});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(path.resolve(__dirname,'../index.html')).href);
 const checks=await page.evaluate(async()=>{
  const out=[],check=(n,b)=>{if(!b)throw Error(n);out.push(n);};
  const click=async s=>{await new Promise(r=>setTimeout(r,215));const b=document.querySelector(s);if(!b||b.disabled)throw Error('Unavailable '+s);b.click();};
  const tab=ch=>document.querySelector(`.cp-chapter-tile[data-cp-chapter="${ch}"]`);
  const reset=()=>{closeModal(false);state=freshState();state.sound=false;save();route('chronicle');};
  const fake=async(ch,mode)=>{const b=document.createElement('button');Object.assign(b.dataset,{cpAction:'start-'+({2:'second',3:'third',4:'fourth'}[ch]),cpMode:mode});document.body.append(b);await new Promise(r=>setTimeout(r,215));b.click();b.remove();};
  reset();check('Only first chapter initially available',!tab(1).disabled&&[2,3,4].every(ch=>tab(ch).disabled));check('Locked tiles explain prerequisite',tab(2).textContent.includes('完成第 1 章后解锁')&&tab(4).textContent.includes('完成第 3 章后解锁'));
  tab(4).disabled=false;await click('.cp-chapter-tile[data-cp-chapter="4"]');check('Forged unlocked tab cannot jump',state.chronicle.run.chapter===1&&$('modalBackdrop').hidden);await fake(3,'carry');await fake(2,'quick');check('Forged start cannot bypass order',state.chronicle.run.chapter===1&&state.cards.encounters.length===0);
  $('cpName').value='小雨';$('cpInstrument').value='长笛';await click('[data-cp-action="enroll"]');check('First enrollment stores identity',state.chronicle.run.name==='小雨'&&state.chronicle.run.inst==='长笛');check('Enrollment alone does not unlock second',tab(2).disabled);
  Object.assign(state.chronicle.run,{ending:'ordinary',scene:'title2',ch:2,tech:17,gold:81,level:4});state.chronicle.run.aff.tim=7;state.chronicle.endings=['ordinary'];save();renderGlobal();check('First completion unlocks only second',!tab(2).disabled&&tab(3).disabled&&tab(4).disabled);
  await fake(2,'quick');check('Quick mode rejected even when unlocked',state.chronicle.run.chapter===1);await click('.cp-chapter-tile[data-cp-chapter="2"]');check('Next chapter opens directly without enrollment or confirmation',$('modalBackdrop').hidden&&!$('cpQuickName')&&!$('cpQuickInst'));check('Second inherits name and instrument',state.chronicle.run.chapter===2&&state.chronicle.run.name==='小雨'&&state.chronicle.run.inst==='长笛');check('Second inherits progression',state.chronicle.run.tech===17&&!('gold' in state.chronicle.run)&&state.chronicle.run.aff.tim===7&&state.chronicle.run.week===1&&!('sta' in state.chronicle.run));check('Chapter still begins with drink offer',state.chronicle.run.scene==='zhu_offer');
  for(const [ch,ending] of [[2,'c2_retry'],[3,'c3_te']]){Object.assign(state.chronicle.run,{ending,scene:'title'+(ch+1),ch:ch+1});state.chronicle.endings.push(ending);save();renderGlobal();check('Completion unlocks chapter '+(ch+1),!tab(ch+1).disabled);if(ch===2)check('Cannot skip newly unlocked third',tab(4).disabled);await click(`.cp-chapter-tile[data-cp-chapter="${ch+1}"]`);check('No repeat form or confirmation for chapter '+(ch+1),$('modalBackdrop').hidden&&!$('cpQuickName'));check('Identity stays consistent in chapter '+(ch+1),state.chronicle.run.name==='小雨'&&state.chronicle.run.inst==='长笛');}
  const scene=state.chronicle.run.scene;await click('.cp-chapter-tile[data-cp-chapter="1"]');await click('[data-cp-action="restart"]');await click('[data-cp-action="confirm-restart"]');check('Replay keeps chapter unlocks',!tab(4).disabled);await click('.cp-chapter-tile[data-cp-chapter="4"]');check('Revisit preserves saved chapter',state.chronicle.run.scene===scene&&state.chronicle.run.name==='小雨');
  const old=freshState();Object.assign(old.chronicle.run,{chapter:4,ch:4,name:'旧玩家',inst:'钢琴',scene:'c4_prep',tech:31,sourceMode:'quick'});const clean=cleanState(old);check('Old skipped chapter parked intact',clean.chronicle.run.chapter===1&&clean.chronicle.slots[4].scene==='c4_prep'&&clean.chronicle.slots[4].tech===31);check('Old identity retained for first chapter',clean.chronicle.run.name==='旧玩家'&&clean.chronicle.run.inst==='钢琴');
  old.chronicle.slots[1]={...Chronicle.fresh().run,name:'初见',inst:'长笛',scene:'title2',ending:'ordinary',tech:29};const preserved=cleanState(old);check('Migration preserves completed first chapter growth',preserved.chronicle.run.name==='初见'&&preserved.chronicle.run.tech===29&&preserved.chronicle.slots[4].name==='初见');
  const gap=freshState();gap.chronicle.endings=['c3_te'];Object.assign(gap.chronicle.run,{chapter:3,ch:4,name:'跳章',scene:'title4',ending:'c3_te'});check('Later ending does not unlock missing chapters',cleanState(gap).chronicle.run.chapter===1);
  save();return out;
 });
 await page.reload();await page.evaluate(()=>route('chronicle'));assert(await page.evaluate(()=>state.chronicle.run.chapter===4&&state.chronicle.run.name==='小雨'&&state.chronicle.run.inst==='长笛'),'Identity and chapter survive actual reload');
 await page.evaluate(()=>{closeModal(false);state=freshState();state.sound=false;save();route('chronicle');});await page.screenshot({path:'/tmp/hjm-chapter-locks.png'});await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'/tmp/hjm-chapter-locks-mobile.png'});assert.deepEqual(errors,[]);console.log('PASS: '+checks.length+' chapter order checks, actual reload and mobile layout.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
