const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE?{executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE}:{})});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(path.resolve(__dirname,'../index.html')).href);
 const checks=await page.evaluate(async()=>{
  const out=[],check=(n,b)=>{if(!b)throw Error(n);out.push(n);};
  const click=async sel=>{await new Promise(r=>setTimeout(r,220));const b=document.querySelector(sel);if(!b||b.disabled)throw Error('Unavailable '+sel);b.click();};
  const reset=()=>{closeModal(false);game.track=0;game.mode='gentle';state=freshState();state.sound=false;save();};
  const scene=(ch,id)=>{state.chronicle.completedChapters=[1,2,3,4,5];Object.assign(state.chronicle.run,{chapter:ch,ch,name:'经济测试',inst:'长笛',scene:id,ending:null});state.chronicle.run.rev++;save();route('chronicle');};
  const pick=n=>click('[data-cp-choice="'+n+'"]');
  const reload=()=>{state=cleanState(JSON.parse(JSON.stringify(state)));save();};
  const finish=(accuracy,{complete=true,hits=10,assists=0,team=false}={})=>{state.cards.encounters=CARD_DEFS.map(c=>c.id);save();state.cards.team=team?['dayang','shiyuan','dijie']:[];state.cards.prepared=team?{id:'dayang',amount:12,token:Date.now()}:null;Object.assign(game,{status:'running',duration:40,elapsed:complete?40:2,notes:Array.from({length:10},()=>({})),score:accuracy*100,perfect:hits,good:0,nice:0,miss:10-hits,combo:hits,maxCombo:hits,cardRun:captureCardRun()});game.cardRun.sourceSnapshot.assists=assists;finishGame();return game.result.reward;};
  reset();check('New balance 30',state.coins===30);check('Retired resources absent',!('sta' in state.chronicle.run)&&!('gold' in state.chronicle.run));
  showGift();$('giftCode').value='MEOW2026';$('redeemGift').click();check('Gift grants 10',state.coins===40);showGift();$('redeemGift').click();check('Gift cannot repeat',state.coins===40);closeModal(false);
  storySession={id:'lala',index:6,choice:0};nextStory();check('Story grants 3',state.coins===43);storySession={id:'lala',index:6,choice:1};nextStory();check('Story cannot repeat',state.coins===43);
  scene(1,'menu');state.coins=10;state.chronicle.run.rev++;renderGlobal();const tech=state.chronicle.run.tech;await click('[data-cp-action="practice"]');check('Practice costs 10 for 2 technique',state.coins===0&&state.chronicle.run.tech===tech+2);check('Practice disables without balance',document.querySelector('[data-cp-action="practice"]').disabled);document.querySelector('[data-cp-action="practice"]').disabled=false;await click('[data-cp-action="practice"]');check('Stale practice cannot overspend',state.coins===0&&state.chronicle.run.tech===tech+2);check('HUD only three useful stats',document.querySelectorAll('.cp-hud>div').length===3&&!document.querySelector('.cp-hud').textContent.match(/体力|团费/));await click('[data-cp-action="earn"]');check('Free earning accessible at zero',currentView==='rhythm');
  for(const ch of [1,2,3,4,5,6]){scene(ch,'b_live');state.chronicle.run.tech=1;state.chronicle.run.week=6;state.coins=9;state.chronicle.run.rev++;renderGlobal();if(ch===6){state.affinity.zhu=10;state.chronicle.endings=['debut','c2_dual','c3_he','c4_he'];state.chronicle.run.rev++;renderGlobal();}check('Extra practice blocks poverty chapter '+ch,document.querySelector('[data-cp-choice="0"]').disabled);state.coins=10;renderGlobal();await pick(0);check('Extra practice charges chapter '+ch,state.coins===0&&state.chronicle.run.tech===3&&state.chronicle.run.week===7);}
  reset();check('One hit cannot farm',finish(10,{hits:1,team:true})===0&&state.economy.daily.rhythm===0);check('Completed ensemble grants each teammate one bond',game.cardRun.bondGains.join(',')==='dayang,shiyuan,dijie'&&state.bondProgress.daily.counts['performance:dayang']===1&&state.bondProgress.daily.counts['performance:shiyuan']===1&&state.bondProgress.daily.counts['performance:dijie']===1&&$('gameOverlay').textContent.includes('大羊、十元、笛杰羁绊分各 +1'));check('Early exit gets no currency',finish(100,{complete:false,team:true})===0);check('Assists alone get no currency',finish(70,{hits:10,assists:10,team:true})===0);check('Failed games do not mark daily rhythm',!state.daily.rhythm);
  for(const [a,base] of [[45,3],[70,4],[85,5],[95,6]]){state.economy.daily.rhythm=0;check('Rank payout '+a,finish(a)===base);state.economy.daily.rhythm=0;check('Team and skill capped '+a,finish(a,{team:true})===base+2);}
  state.economy.daily.rhythm=0;check('First high rank reward',finish(100,{team:true})===8);check('Second high rank reward',finish(100,{team:true})===8);check('Third high rank reward',finish(100,{team:true})===8);const balance=state.coins;finishGame();check('Double finish cannot reward',state.coins===balance);reload();check('Fourth total is 1 after reload',finish(100,{team:true})===1&&game.result.cardBonus===0);state.economy.daily.date='2000-01-01';check('New day restores first-three rewards',finish(100,{team:true})===8&&state.economy.daily.rhythm===1);
  state.daily.pet=state.daily.story=true;renderGlobal();const beforeDaily=state.coins;$('dailyClaim').click();$('dailyClaim').click();check('Daily 10 once',state.coins===beforeDaily+10);
  reset();scene(2,'c2_sponsor');await pick(1);check('Sponsor gives 5 notes',state.coins===35);state.chronicle.run.events.sponsor=null;scene(2,'c2_sponsor');await pick(1);check('Sponsor cannot repeat',state.coins===35);scene(4,'c4_qiqi');await pick(2);check('Fourth sponsor gives 5',state.coins===40);reload();scene(4,'c4_qiqi');await pick(2);check('Fourth sponsor persists',state.coins===40);
  scene(4,'c4_band_lemon');state.coins=19;renderGlobal();check('Loan blocks insufficient balance',document.querySelector('[data-cp-choice="0"]').disabled);state.coins=20;renderGlobal();await pick(0);check('Loan uses unified balance',state.coins===0);
  for(const [ch,id,index,gain] of [[3,'c3_band_bill',1,1],[4,'c4_band_bao',1,1],[5,'c5_band_y',0,2],[6,'c6_band_zhu',1,1],[6,'c6_zhu',1,1]]){scene(ch,id);const t=state.chronicle.run.tech;await pick(index);check('Plot technique first '+id,state.chronicle.run.tech===t+gain);reload();scene(ch,id);await pick(index);check('Plot technique cannot repeat '+id,state.chronicle.run.tech===t+gain);}
  reset();scene(1,'practice_turn');const t=state.chronicle.run.tech;state.affinity.lala=10;const battle=async()=>{scene(1,'practice_turn');state.chronicle.run.battle={hp:100,maxHp:100,pressure:1,round:1,partner:'lala',over:false,win:false};state.chronicle.run.rev++;renderGlobal();await click('[data-cp-battle="duet"]');};await battle();check('Free duet does not add technique',state.chronicle.run.tech===t);check('First battle grants 3 daily plus 3 first',state.coins===36);await battle();check('Repeat battle grants no coins',state.coins===36);reload();await battle();check('Battle cap persists',state.coins===36);
  reset();scene(1,'s_dream');const initial=state.coins;await pick(2);check('Chapter first completion grants 15',state.coins===initial+15);scene(1,'live_play');state.chronicle.run.live={scores:[10,10,10,10,10],score:50,diff:16,pos:50,dir:1,phase:'feedback',last:'',finished:false,width:30};state.chronicle.run.rev++;renderGlobal();await click('[data-cp-action="live-next"]');check('Different ending cannot stack currency',state.coins===initial+15);check('Different ending still collected',state.chronicle.endings.includes('debut'));await click('[data-cp-action="restart"]');await click('[data-cp-action="confirm-restart"]');check('Restart keeps ledger',state.economy.claimed['chapter:1']);
  scene(3,'s_dream');const beforeShared=state.coins;await pick(2);check('Shared ending pays once in each completed chapter',state.coins===beforeShared+15&&state.economy.claimed['chapter:3']);
  reset();state.cards.encounters=CARD_DEFS.map(c=>c.id);state.affinity.azhe=35;save();expansion().azhe.tickets=3;
  const applause=async()=>{expansion().azhe.applauseMs=29999;startAzheApplause();$('applauseBegin').click();await new Promise(r=>setTimeout(r,350));closeModal(false);};
  await applause();check('First encore grants 2',state.coins===32);reload();await applause();check('Second encore retains noncurrency effect but no notes',state.coins===32&&expansion().azhe.encores===2);state.economy.daily.date='2000-01-01';await applause();check('Encore resets next day',state.coins===34);
  const old=freshState();delete old.economy;delete old.progression;old.coins=321;old.affinity.lala=37;old.cat.aff=12;Object.assign(old.chronicle.run,{name:'旧档',scene:'title2',ending:'debut',level:4,gold:999,sta:10});old.chronicle.endings=['debut'];old.chronicle.claimed=['debut','audition'];old.chronicle.slots[2]={...Chronicle.fresh().run,chapter:2,name:'旧档',scene:'menu',level:3,events:{sponsor:'accepted'},gold:300,sta:9};state=cleanState(old);check('Migration preserves existing growth and starts band at level one',state.coins===321&&cardBond('lala')===37&&state.cat.aff===12&&globalOrchestraLevel()===4&&globalBandLevel()===1);check('Migration removes retired resources everywhere',![state.chronicle.run,...Object.values(state.chronicle.slots)].some(r=>'gold'in r||'sta'in r));check('Legacy ending and sponsor blocked',state.economy.claimed['chapter:1']&&state.economy.claimed.audition&&state.economy.claimed['plot:2:c2_sponsor']);const ledger=JSON.stringify(state.economy);reload();check('Migration idempotent',state.coins===321&&JSON.stringify(state.economy)===ledger);
  let plainImportRejected=false;try{cleanImportedState(old);}catch(e){plainImportRejected=/缺少完整的加密成长数据/.test(e.message);}check('Plain-text file import is rejected',plainImportRejected);
  const protectedSave=persistedState(),protectedText=JSON.stringify(protectedSave);
  check('Protected values are not persisted in plain text',!Object.hasOwn(protectedSave,'coins')&&!Object.hasOwn(protectedSave,'affinity')&&!Object.hasOwn(protectedSave,'progression')&&protectedSave.bondVault.v===3&&!!protectedSave.wallet&&!!protectedSave.bondVault&&!!protectedSave.levelVault&&!protectedText.includes('"coins":321')&&!allChronicleRuns(protectedSave.chronicle).some(run=>Object.hasOwn(run,'aff')||Object.hasOwn(run,'level')));
  const protectedRoundTrip=cleanImportedState(protectedSave);check('Protected import round trips',protectedRoundTrip.coins===321&&protectedRoundTrip.affinity.lala===37&&protectedRoundTrip.cat.aff===12&&globalOrchestraLevel(protectedRoundTrip)===4&&globalBandLevel(protectedRoundTrip)===1);
  const beforeRoster=JSON.parse(protectedText);beforeRoster.bondVault.v=1;delete beforeRoster.bondVault.values.xiaojie;delete beforeRoster.bondVault.values.rek;delete beforeRoster.bondVault.values.aqi;
  const rosterMigrated=cleanImportedState(beforeRoster);check('Bond vault v1 safely seeds later Xiaojie REK and A-Qi bonds',rosterMigrated.affinity.xiaojie===0&&rosterMigrated.affinity.rek===0&&rosterMigrated.affinity.aqi===0&&rosterMigrated.affinity.lala===37);
  const v2Roster=JSON.parse(protectedText);v2Roster.bondVault.v=2;delete v2Roster.bondVault.values.aqi;delete v2Roster.cards.collection.aqi;
  const v2Migrated=cleanImportedState(v2Roster);check('Previous v2 vault seeds only the newly added A-Qi fields',v2Migrated.affinity.aqi===0&&!v2Migrated.cards.collection.aqi.owned&&v2Migrated.affinity.lala===37&&v2Migrated.coins===321);
  const missingCurrentBond=JSON.parse(protectedText);delete missingCurrentBond.bondVault.values.aqi;let rejected=false;try{cleanImportedState(missingCurrentBond);}catch(e){rejected=/成长数据校验失败/.test(e.message);}check('Bond vault v3 still rejects deleted roster values',rejected);
  state.progression.bandLevel=2;const accidentalBandSave=persistedState();accidentalBandSave.levelVault.v=1;check('Accidental coupled band gain is reset once',globalBandLevel(cleanImportedState(accidentalBandSave))===1);state.progression.bandLevel=1;
  const legacyBondInjection=JSON.parse(protectedText);legacyBondInjection.cards.trio.tim.performance=100;check('Protected bonds ignore retired plain-text meters',cleanImportedState(legacyBondInjection).affinity.tim===protectedRoundTrip.affinity.tim);
  const tampered=JSON.parse(protectedText);tampered.wallet.c=(tampered.wallet.c[0]==='0'?'1':'0')+tampered.wallet.c.slice(1);rejected=false;try{cleanImportedState(tampered);}catch(e){rejected=/音符数据校验失败/.test(e.message);}check('Tampered wallet is rejected',rejected);
  const bondTampered=JSON.parse(protectedText);bondTampered.bondVault.values.lala.c=(bondTampered.bondVault.values.lala.c[0]==='0'?'1':'0')+bondTampered.bondVault.values.lala.c.slice(1);rejected=false;try{cleanImportedState(bondTampered);}catch(e){rejected=/成长数据校验失败/.test(e.message);}check('Tampered bond is rejected',rejected);
  const levelTampered=JSON.parse(protectedText);levelTampered.levelVault.band.c=(levelTampered.levelVault.band.c[0]==='0'?'1':'0')+levelTampered.levelVault.band.c.slice(1);rejected=false;try{cleanImportedState(levelTampered);}catch(e){rejected=/成长数据校验失败/.test(e.message);}check('Tampered level is rejected',rejected);
  localStorage.removeItem(KEY);localStorage.setItem(V61_KEY,JSON.stringify(old));loadState();check('Plain-text browser save still loads only from legacy key',state.coins===321&&cardBond('lala')===37&&globalBandLevel()===1);save();const migrated=JSON.parse(localStorage.getItem(KEY));check('Plain-text browser save migrates to strict current key',!localStorage.getItem(V61_KEY)&&!Object.hasOwn(migrated,'coins')&&!Object.hasOwn(migrated,'affinity')&&!Object.hasOwn(migrated,'progression')&&migrated.bondVault.v===3&&!!migrated.levelVault&&cleanState(migrated).coins===321);localStorage.removeItem(BACKUP_KEY);localStorage.removeItem(RECOVERY_KEY);const forgedCurrent={...old},forgedText=JSON.stringify(forgedCurrent);localStorage.setItem(KEY,forgedText);loadState();check('Unreadable current save pauses persistence instead of rebuilding',state.coins===30&&!storageOK&&localStorage.getItem(RECOVERY_KEY)===forgedText);showSettings();check('Recovery mode exposes the untouched raw save download',!!document.querySelector('#exportRecoverySave'));closeModal(false);save();check('Startup save cannot overwrite unreadable original',localStorage.getItem(KEY)===forgedText);state=cleanState(migrated);storageOK=true;storageRecovered=true;storageLoadError='';save();const knownGood=localStorage.getItem(KEY);state.coins=300;save();check('Successful saves maintain a last-known-good backup',localStorage.getItem(BACKUP_KEY)===knownGood);localStorage.setItem(KEY,forgedText);loadState();check('Unreadable current save automatically restores valid backup',storageOK&&storageRecovered&&state.coins===321&&storageLoadError.includes('自动恢复'));save();check('Recovered backup replaces broken current without poisoning backup',cleanImportedState(JSON.parse(localStorage.getItem(KEY))).coins===321&&localStorage.getItem(BACKUP_KEY)===knownGood);
  scene(1,'menu');save();return out;
 });
 await page.reload();assert.equal(await page.evaluate(()=>state.coins),321);await page.evaluate(()=>route('chronicle'));for(const width of [1440,390]){await page.setViewportSize({width,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No overflow '+width);await page.screenshot({path:'/tmp/hjm-economy-'+width+'.png',fullPage:true});}await page.evaluate(()=>route('rhythm'));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Rhythm mobile layout');await page.screenshot({path:'/tmp/hjm-economy-rhythm.png',fullPage:true});assert.deepEqual(errors,[]);console.log('PASS: '+checks.length+' economy checks, actual reload, desktop/mobile layout.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
