const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE?{executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE}:{})});try{const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(path.resolve(__dirname,'../index.html')).href);
const checks=await page.evaluate(async()=>{
 const out=[],check=(n,b)=>{if(!b)throw Error(n);out.push(n);};const click=async s=>{await new Promise(r=>setTimeout(r,215));const b=document.querySelector(s);if(!b||b.disabled)throw Error(s);b.click();};
 const legacy=freshState();delete legacy.chronicle.bonds;legacy.chronicle.completedChapters=[1,2,3];
 const run=(ch,aff)=>({...Chronicle.fresh().run,chapter:ch,ch,name:'全局测试',inst:'长笛',sourceMode:'carry',scene:'menu',flags:ch===2?{strGroup:1}:{},aff:{...Chronicle.fresh().run.aff,...aff}});
 legacy.chronicle.run=run(3,{zhu:14,tim:5});legacy.chronicle.slots={1:run(1,{zhu:3,tim:12}),2:run(2,{zhu:8,tim:10}),4:run(4,{zhu:0,tim:0})};legacy.chronicle.chapter2Start=run(2,{yeshiyang:9});
 state=cleanState(legacy);state.sound=false;state.cards.encounters=['zhu','tim','shiyuan','lemon'];save();route('chronicle');
 check('Historic maximum chosen per character',state.chronicle.bonds.zhu===14&&state.chronicle.bonds.tim===12&&state.chronicle.bonds.yeshiyang===9);check('All chapters share same global bonds',Object.values(state.chronicle.slots).every(r=>r.aff===state.chronicle.bonds)&&state.chronicle.run.aff===state.chronicle.bonds);
 for(const ch of [4,1,2,3]){await click(`.cp-chapter-tile[data-cp-chapter="${ch}"]`);check('Chapter '+ch+' shows global values',state.chronicle.run.aff.zhu===14&&state.chronicle.run.aff.tim===12);}
 await click('[data-cp-action="social"]');await click('[data-cp-action="chat"][data-cp-person="zhu"]');check('Chat increases global bond',state.chronicle.bonds.zhu===16);await click('[data-cp-choice="0"]');await click('.cp-chapter-tile[data-cp-chapter="1"]');check('Earlier chapter sees new affinity',state.chronicle.run.aff.zhu===16);await click('[data-cp-action="restart"]');await click('[data-cp-action="confirm-restart"]');check('First chapter restart cannot clear bonds',state.chronicle.run.aff.zhu===16&&state.chronicle.run.aff.tim===12);await click('.cp-chapter-tile[data-cp-chapter="3"]');await click('[data-cp-action="restart"]');await click('[data-cp-action="confirm-restart"]');check('Later chapter restart cannot clear bonds',state.chronicle.run.aff.zhu===16&&state.chronicle.run.aff.tim===12);
 await click('.cp-chapter-tile[data-cp-chapter="2"]');Object.assign(state.chronicle.run,{scene:'c2_boundary',ending:null});state.chronicle.run.rev++;save();renderGlobal();await click('[data-cp-choice="1"]');check('Former negative dialogue choice cannot lower bond',state.chronicle.bonds.tim===12);
 await click('.cp-chapter-tile[data-cp-chapter="3"]');Object.assign(state.chronicle.run,{scene:'menu',week:1,ending:null});state.chronicle.run.aff.tim=70;state.chronicle.run.rev++;save();renderGlobal();await click('[data-cp-action="end-week"]');check('Gossip cannot deduct global bonds',state.chronicle.bonds.tim===70);
 state.chronicle.run.aff.shiyuan=98;Object.assign(state.chronicle.run,{scene:'chat_select',ending:null});state.chronicle.run.rev++;save();renderGlobal();await click('[data-cp-action="chat"][data-cp-person="shiyuan"]');check('Threshold ending never resets accumulated bonds',state.chronicle.bonds.shiyuan===100&&state.chronicle.run.ending==='shadow');await click('[data-cp-action="restart"]');await click('[data-cp-action="confirm-restart"]');check('Threshold restart retains hundred bond',state.chronicle.run.aff.shiyuan===100);await click('[data-cp-choice="4"]');await click('[data-cp-choice="0"]');check('Replay is not trapped by persistent threshold',!state.chronicle.run.ending&&state.chronicle.run.scene==='c3_intro');
 const before=JSON.stringify(state.chronicle.bonds);Chronicle.requestLegacy({name:'导入',inst:'小提琴',scene:'c2_tim',ch:2,week:1,tech:12,aff:{tim:0,zhu:0}});$('cpConfirmLegacy').click();check('Chapter import cannot lower existing global bonds',state.chronicle.bonds.zhu===16&&state.chronicle.bonds.tim===70&&state.chronicle.bonds.shiyuan===100);check('Sidebar labels global values',$('view-chronicle').textContent.includes('全局 · 正传羁绊'));
 const once=JSON.stringify(state.chronicle.bonds);state=cleanState(JSON.parse(JSON.stringify(state)));check('Repeated migration never adds twice',JSON.stringify(state.chronicle.bonds)===once);save();return out;
});await page.reload();await page.evaluate(()=>route('chronicle'));assert(await page.evaluate(()=>state.chronicle.bonds.zhu===16&&state.chronicle.run.aff.tim===70&&Object.values(state.chronicle.slots).every(r=>r.aff.zhu===16)),'Actual reload preserves global affinity');assert.deepEqual(errors,[]);console.log('PASS: '+checks.length+' global-bond checks and actual reload.');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
