const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE?{executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE}:{})});try{const p=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(pathToFileURL(path.resolve(__dirname,'../index.html')).href);const results=await p.evaluate(()=>{
 const checks=[],check=(name,ok)=>{if(!ok)throw Error(name);checks.push(name);};state=freshState();state.sound=false;
 check('Eighteen unique cards',CARD_DEFS.length===18&&new Set(CARD_DEFS.map(c=>c.id)).size===18);
 check('No duplicate memory records',new Set(MEMORIES.map(m=>m.id)).size===MEMORIES.length);
 check('Unmentioned Dayang and Baoshi remain locked',!cardOwned('dayang')&&!cardOwned('baoshi')&&!availableCardPool().some(c=>['dayang','baoshi'].includes(c.id)));
 state.cards.encounters=CARD_DEFS.map(c=>c.id);save();
 check('New source rarities',cardRarity(cardDef('xiaozhou'))==='R'&&cardRarity(cardDef('lemon'))==='UR'&&['dayang','baoshi','goose','xiaota'].every(id=>cardRarity(cardDef(id))==='SSR'));
 check('Only Bill remains placeholder',CARD_DEFS.filter(c=>c.placeholder).map(c=>c.id).join()==='bill');
 check('Bill absent from recruit pool',!availableCardPool().some(c=>c.id==='bill'));
 goCard('baoshi');check('Secret absent from locked DOM',!$('view-card').innerHTML.includes('宝石姬')&&!$('view-card').innerHTML.includes('新裙子'));
 addCardBond('baoshi',20);goCard('baoshi');check('Secret unlocks collapsed',$('view-card').innerHTML.includes('宝石姬')&&!$('view-card').innerText.includes('宝石姬'));check('Hidden gift appears after unlock',effectiveGifts(cardDef('baoshi')).length===4);
 state.cards.team=['xiaozhou'];onSourceGift(cardDef('xiaozhou'),cardDef('xiaozhou').gifts.find(g=>g[0]==='praise'));prepareSourceSkill('xiaozhou');check('Praise doubles active reward',state.cards.prepared.amount===12);state=cleanState(JSON.parse(JSON.stringify(state)));check('Prepared dynamic reward persists',state.cards.prepared.amount===12);
 const perform=(ids)=>{state.cards.team=ids;game.cardRun=captureCardRun();game.notes=[];awardCardPerformance(1);};
 perform(['xiaozhou','goose']);check('Goose present prevents solo growth',sourceCast().xiaozhou.solos===0);
 for(let i=0;i<3;i++)perform(['xiaozhou']);check('Three solo performances evolve card',sourceCast().xiaozhou.solos===3&&cardRarity(cardDef('xiaozhou'))==='SR'&&cardStarCount(cardDef('xiaozhou'))===3);const solos=sourceCast().xiaozhou.solos;awardCardPerformance(1);check('No duplicate performance credit',sourceCast().xiaozhou.solos===solos);
 state.cards.team=['dayang'];prepareSourceSkill('dayang');check('Online guitar bonus',state.cards.prepared.amount===12);state=cleanState(JSON.parse(JSON.stringify(state)));check('Online bonus survives reload cleaning',state.cards.prepared.amount===12);sourceCast().dayang.online=false;state.cards.prepared=null;prepareSourceSkill('dayang');check('Offline guitar bonus',state.cards.prepared.amount===8);
 state.cards.team=['baoshi','dayang'];prepareSourceSkill('baoshi');const bond=cardBond('dayang');perform(['baoshi','dayang']);check('Baoshi purification and team bond',sourceCast().baoshi.purity===50&&cardBond('dayang')===bond+5);
 resolveLemonChallenge('xiaozhou','serious');check('Lemon comparison reduces next Xiaozhou active',sourceSkillAmount('xiaozhou')===3&&sourceCast().lemon.result.includes('输了'));const result=sourceCast().lemon.result;resolveLemonChallenge('dayang','ignore');check('Challenge cooldown blocks repeat',sourceCast().lemon.result===result);
 state.cards.team=['xiaota'];prepareSourceSkill('xiaota');game.cardRun=captureCardRun();Object.assign(game,{good:0,nice:0,perfect:0,score:0,combo:0,maxCombo:0,miss:0});const random=Math.random;Math.random=()=>.99;try{const note={lane:0};settleLateNote(note,0);check('Prepared Xiaota rescue overrides random',game.good===1&&game.cardRun.sourceSnapshot.rescued&&note.hit);settleLateNote({lane:0},1);check('Rescue can only happen once',game.good===1&&game.miss===1);}finally{Math.random=random;}
 const before=state.coins;check('Automatic assists alone give no rewards',awardCardPerformance(0)===0&&state.coins===before&&!game.cardRun.credited);
 state.cards.team=['lemon','baoshi'];addCardBond('lemon',10);check('Lemon threshold is strictly greater than ten',!sourceCast().lemon.ended);addCardBond('lemon',1);check('Lemon BE removes only Lemon from lineup',sourceCast().lemon.ended&&state.cards.team.join()==='baoshi'&&cardOwned('baoshi'));closeModal(false);
 state=cleanState(JSON.parse(JSON.stringify(state)));check('Evolution and BE persist',cardRarity(cardDef('xiaozhou'))==='SR'&&sourceCast().lemon.ended&&sourceCast().baoshi.purity===50);
 state.cards.team=['qiqi','lala'];hostQiqiParty();check('Qiqi cares for female Lala too',qiqiState().cared.includes('lala'));
 save();goCard('dayang');return checks;
 });for(const [key,url] of await p.evaluate(()=>Object.entries(ASSETS))){assert(!url.startsWith('data:'),key+' uses external asset');assert(await p.evaluate(async url=>{const i=new Image();i.src=url;try{await i.decode();return i.naturalWidth>0;}catch{return false;}},url),key+' image loads');}await p.waitForTimeout(100);await p.evaluate(()=>{closeModal(false);document.querySelectorAll('.toast').forEach(e=>e.remove());goCard('dayang');});await p.screenshot({path:'/tmp/hjm-dayang-desktop.png'});await p.setViewportSize({width:390,height:844});for(const id of ['dayang','baoshi','goose','xiaozhou','lemon','xiaota','qiqi']){await p.evaluate(id=>goCard(id),id);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),id+' mobile overflow');}await p.screenshot({path:'/tmp/hjm-qiqi-final.png'});await p.reload();assert(await p.evaluate(()=>cardRarity(cardDef('xiaozhou'))==='SR'&&sourceCast().lemon.ended),'Actual reload persists evolution and ending');assert.deepEqual(errors,[]);console.log('PASS: '+results.length+' source-card behavior checks, 7 mobile cards, actual reload, no runtime errors.');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
