const {chromium}=require('playwright');const {pathToFileURL}=require('node:url');const path=require('node:path');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE?{executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE}:{})});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(path.resolve(__dirname,'../index.html')).href);
 const checks=await page.evaluate(async()=>{
  const out=[],check=(label,ok)=>{if(!ok)throw Error(label+' at '+state.chronicle.run.scene);out.push(label);};
  const click=async s=>{await new Promise(r=>setTimeout(r,215));const b=document.querySelector(s);if(!b||b.disabled)throw Error('Missing '+s);b.click();};const pick=n=>click(`[data-cp-choice="${n}"]`);
  const reset=()=>{closeModal(false);state=freshState();state.sound=false;save();route('home');};
  const reload=()=>{state=cleanState(JSON.parse(JSON.stringify(state)));save();route('chronicle');};
  const enter=async ch=>{state.chronicle.completedChapters=Array.from({length:ch-1},(_,i)=>i+1);state.chronicle.run.rev++;renderGlobal();await click(`[data-cp-action="switch-chapter"][data-cp-chapter="${ch}"]`);};
  const first=async()=>{reset();route('chronicle');$('cpName').value='新乐手';$('cpInstrument').value='长笛';await click('[data-cp-action="enroll"]');check('First venue is Shanqiu',$('cpStoryText').textContent.includes('山丘酒吧'));await pick(0);await pick(0);check('Shiyuan speaks before owner',state.chronicle.run.scene==='s_shi'&&!cardOwned('zhu'));await pick(0);check('Owner offers menu after Shiyuan',state.chronicle.run.scene==='zhu_offer'&&cardOwned('zhu')&&!cardOwned('kongge'));};
  reset();check('New game starts with 30 notes',state.coins===30);const old=JSON.parse(JSON.stringify(state));old.coins=30;check('Old balance is preserved',cleanState(old).coins===30);check('Card roster has 20 entries',CARD_DEFS.length===20);
  for(const [index,id,cost,bond] of [[0,'lemon',10,1],[1,'martini',10,1],[2,'mojito',10,1],[3,'long-island',10,1],[4,'decline',0,0]]){
   await first();const gold=state.chronicle.run.gold;await pick(index);check('Order records '+id,state.chronicle.run.bar.order===id);check('Price and affinity '+id,state.coins===30-cost&&state.chronicle.run.aff.zhu===bond&&state.chronicle.run.gold===gold);check('Drink name does not unlock Lemon',!cardOwned('lemon'));reload();check('Order survives save '+id,state.chronicle.run.bar.order===id&&state.coins===30-cost);await pick(0);check('Bar continues the opening without advancing time '+id,state.chronicle.run.week===1&&state.chronicle.run.weekly.done.includes(1));check('First chapter rejoins '+id,state.chronicle.run.scene==='s_first'&&cardOwned('kongge'));
  }
  await first();state.coins=4;state.chronicle.run.rev++;renderGlobal();check('Cannot buy without notes',document.querySelector('[data-cp-choice="0"]').disabled);document.querySelector('[data-cp-choice="0"]').disabled=false;await pick(0);check('Stale menu cannot overspend',state.coins===4&&state.chronicle.run.bar.order===null);await pick(4);check('Refusal is free and adds no affinity',state.coins===4&&state.chronicle.run.aff.zhu===0);
  await first();await pick(4);await pick(0);await enter(2);check('Chapter two starts with bar',state.chronicle.run.scene==='zhu_offer');await pick(4);await pick(0);check('Chapter two rejoins',state.chronicle.run.scene==='c2_intro');await enter(3);await pick(4);await pick(0);check('Chapter three rejoins',state.chronicle.run.scene==='c3_intro');check('No chapter subsidy',state.coins===30);reload();await enter(4);
  check('Three refusals close bar at fourth entrance',state.chronicle.run.scene==='shanqiu_closed'&&state.chronicle.run.bar.closed&&!$('modalBackdrop').hidden&&$('modalContent').textContent.includes('停业'));
  check('Closure has external illustration',$('modalContent').querySelector('img').getAttribute('src')==='assets/shanqiu-closed.webp');
  reload();check('Unacknowledged closure persists',state.chronicle.run.scene==='shanqiu_closed');await click('#modalContent [data-cp-action="bar-continue"]');check('Closure memory once and free treat',state.chronicle.run.scene==='zhu_offer'&&state.memories.includes('shanqiu_closed')&&document.querySelector('.shanqiu-menu').textContent.includes('这次我请'));await pick(0);check('Closure treat does not charge notes',state.coins===30&&state.chronicle.run.bar.closed);await pick(0);reload();check('Acknowledged popup does not repeat',$('modalBackdrop').hidden&&state.chronicle.run.bar.closureSeen);
  // Any purchase in any of the first three chapters prevents closure.
  for(let paid=1;paid<=3;paid++){
   reset();Object.assign(state.chronicle.run,{name:'新乐手',scene:'s_first',bar:{order:paid===1?'lemon':'decline',returnTo:'s_first',closed:false,closureSeen:false}});state.chronicle.slots[2]={...Chronicle.fresh().run,chapter:2,ch:2,name:'新乐手',scene:'c2_intro',bar:{order:paid===2?'mojito':'decline'}};state.chronicle.slots[3]={...Chronicle.fresh().run,chapter:3,ch:3,name:'新乐手',scene:'c3_intro',bar:{order:paid===3?'martini':'decline'}};save();route('chronicle');await enter(4);check('A drink in chapter '+paid+' keeps bar open',!state.chronicle.run.bar.closed&&state.chronicle.run.scene==='c4_intro'&&!document.querySelector('.shanqiu-menu'));
  }
  reset();Object.assign(state.chronicle.run,{name:'新乐手',inst:'长笛'});state.chronicle.slots[3]={...Chronicle.fresh().run,chapter:3,ch:4,name:'新乐手',inst:'长笛',scene:'title4',ending:'c3_te'};route('chronicle');await enter(4);check('Legacy missing drink records do not imply refusal',!state.chronicle.run.bar.closed&&state.chronicle.run.scene==='c4_intro');const balance=state.coins;await click('[data-cp-action="restart"]');await click('[data-cp-action="confirm-restart"]');check('Fourth restart has no drink menu or subsidy',state.chronicle.run.scene==='c4_intro'&&state.chronicle.run.bar.order===null&&state.coins===balance);state.cards.encounters.push('zhu');save();
  goCard('zhu');check('SSR four-star source card',cardDef('zhu').rarity==='SSR'&&cardDef('zhu').stars===4);check('Card attributes conceal bartending',sourceStat(cardDef('zhu'),'调酒',96)==='??'&&!$('view-card').innerHTML.includes('深夜吧台')&&!$('view-card').innerHTML.includes('拾光'));check('Three public skills present',['幽灵项目落地器','无视和弦','卡祖笛小号'].every(s=>$('view-card').innerText.includes(s)));
  state.affinity.zhu=35;renderCardPage();check('Ready skill still conceals number',sourceStat(cardDef('zhu'),'调酒',96)==='??'&&!$('view-card').innerHTML.includes('拾光'));await click('[data-zhu-reveal]');check('Explicit reveal shows number, story and new gift',sourceStat(cardDef('zhu'),'调酒',96)===96&&$('view-card').innerText.includes('深夜吧台')&&cardGifts(cardDef('zhu')).some(g=>g[0]==='night'));reload();goCard('zhu');check('Reveal persists',state.cards.zhuNight&&state.memories.includes('zhu_night'));
  state.cards.team=['zhu'];prepareSourceSkill('zhu');check('Active prepares eight-note bonus',state.cards.prepared?.amount===8);game.cardRun=captureCardRun();Object.assign(game,{nice:0,good:0,miss:0,score:0,combo:0,maxCombo:0});const n={lane:0};settleLateNote(n,0);check('Kazoo rescues first missing wind note',n.hit&&game.nice===1&&game.cardRun.sourceSnapshot.assists===1);const n2={lane:1};settleLateNote(n2,1);check('Kazoo only rescues once',n2.missed&&game.miss===1);
  state.cards.team=['zhu','dijie'];game.cardRun=captureCardRun();const n3={lane:0};settleLateNote(n3,2);check('Wind presence disables kazoo substitute',n3.missed);
  save();goCard('zhu');return out;
 });
 await page.reload();assert(await page.evaluate(()=>state.cards.zhuNight));await page.evaluate(()=>goCard('zhu'));await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.waitForTimeout(450);await page.screenshot({path:'/tmp/hjm-zhu-mobile.png',fullPage:true});
 await page.evaluate(()=>{closeModal(false);state=freshState();state.sound=false;state.chronicle.completedChapters=[1,2,3];for(const ch of [1,2,3])state.chronicle.slots[ch]={...Chronicle.fresh().run,chapter:ch,name:'新乐手',bar:{order:'decline'},scene:ch===1?'s_first':'c'+ch+'_intro'};Object.assign(state.chronicle.run,{chapter:4,ch:4,name:'新乐手',scene:'shanqiu_closed',bar:{order:null,returnTo:'c4_intro',closed:true,closureSeen:false}});save();});
 await page.reload();await page.evaluate(()=>route('chronicle'));assert(await page.evaluate(()=>state.chronicle.run.scene==='shanqiu_closed'&&!$('modalBackdrop').hidden),'Closure popup survives actual reload');await page.waitForTimeout(450);await page.screenshot({path:'/tmp/hjm-shanqiu-closed-mobile.png',fullPage:true});
 await page.click('#modalContent [data-cp-action="bar-continue"]');await page.reload();await page.evaluate(()=>route('chronicle'));assert(await page.evaluate(()=>state.chronicle.run.scene==='zhu_offer'&&state.chronicle.run.bar.closureSeen&&$('modalBackdrop').hidden),'Acknowledgment and free treat survive actual reload');await page.waitForTimeout(450);await page.screenshot({path:'/tmp/hjm-shanqiu-menu-mobile.png',fullPage:true});
 assert.deepEqual(errors,[]);console.log(`PASS: ${checks.length} Zhu/card/bar checks, reload, mobile, no runtime errors.`);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
