"""Rebuild the tiny embedded click bank from the user's metronome recording.

Requires ffmpeg; no Python dependencies. The generated classic JS script embeds
mono PCM, so the game works over file:// without fetching or decoding audio.
"""
from pathlib import Path
import array
import base64
import json
import math
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets/audio/rhythm-audition/source/metronome-reference-2026-10.mp4"
TARGET = ROOT / "js/audio/rhythm-audition-voices.js"
SAMPLE_RATE = 44100


def extract(start, length):
    raw = subprocess.check_output([
        "ffmpeg", "-v", "error", "-i", str(SOURCE), "-ss", str(start),
        "-t", str(length), "-vn", "-ac", "1", "-ar", str(SAMPLE_RATE),
        "-f", "f32le", "pipe:1",
    ])
    samples = array.array("f", raw)
    if sys.byteorder != "little":
        samples.byteswap()
    peak = max(map(abs, samples))
    # Remove codec pre-roll, but retain the recording's actual attack/decay.
    onset = next(i for i, value in enumerate(samples) if abs(value) > peak * .015)
    samples = samples[max(0, onset - 16):]
    dc = sum(samples) / len(samples)
    result = [value - dc for value in samples]
    peak = max(map(abs, result))
    for i in range(len(result)):
        attack = min(1, i / 16)
        release = min(1, (len(result) - 1 - i) / 350)
        result[i] *= .94 / peak * attack * release
    return result


def pitch_up(samples, rate):
    # Preserve the percussive transient: change pitch and length together, not BPM.
    result = []
    for i in range(int((len(samples) - 1) / rate)):
        position = i * rate
        index = int(position)
        fraction = position - index
        result.append(samples[index] * (1 - fraction) + samples[index + 1] * fraction)
    scale = .94 / max(map(abs, result))
    return [value * scale for value in result]


def encode(samples):
    pcm = array.array("h", (round(max(-1, min(1, value)) * 32767) for value in samples))
    if sys.byteorder != "little":
        pcm.byteswap()
    return {"frames": len(pcm), "pcm16": base64.b64encode(pcm.tobytes()).decode("ascii")}


def legacy_count_in(accent=False):
    """Restore the former 90 ms metallic cue, without the old clipping gain."""
    result = [0.0] * round(.09 * SAMPLE_RATE)
    for ratio, level, index in [(1, 1, 0), (1.414, .42, 1), (2.093, .18, 2)]:
        duration = .09 * (1 - index * .15)
        frequency = 1680 * ratio * (1.18 if accent else 1)
        glide_end = duration * .72
        glide_rate = math.log(.985) / glide_end
        hold_end = duration * .82
        for frame in range(math.ceil(duration * SAMPLE_RATE)):
            time = frame / SAMPLE_RATE
            if time < .003:
                envelope = .0001 * (level / .0001) ** (time / .003)
            elif time <= hold_end:
                envelope = level
            else:
                envelope = level * (.0001 / level) ** ((time - hold_end) / (duration - hold_end))
            glide_time = min(time, glide_end)
            cycles = frequency * math.expm1(glide_rate * glide_time) / glide_rate
            cycles += max(0, time - glide_end) * frequency * .985
            result[frame] += math.sin(2 * math.pi * cycles) * envelope
    scale = .94 / max(map(abs, result))
    result = [value * scale for value in result]
    result[-1] = 0
    return result


def main():
    strong = extract(.536, .224)
    normal = extract(1.155, .108)
    samples = {"accent": encode(strong), "normal": encode(normal), "tap": encode(pitch_up(normal, 1.5)),
               "countIn": encode(legacy_count_in()), "countInAccent": encode(legacy_count_in(True))}
    bank = {"sampleRate": SAMPLE_RATE, "samples": samples}
    script = """'use strict';

// Generated by scripts/build-rhythm-audition-voices.py: reference hits + legacy pre-roll.
// Short, normalized single hits only. No network fetch or codec startup latency.
const RHYTHM_AUDITION_VOICES = (() => {
    const bank = __BANK__;
    const profiles = Object.freeze({
        countIn: Object.freeze({waveform:'legacy-metallic',sample:'countIn',fundamentalHz:1680,duration:.09,gain:1}),
        countInAccent: Object.freeze({waveform:'legacy-metallic',sample:'countInAccent',fundamentalHz:1680*1.18,duration:.09,gain:1}),
        metronome: Object.freeze({waveform:'sample',sample:'normal',fundamentalHz:720,duration:bank.samples.normal.frames/bank.sampleRate,gain:1}),
        accent: Object.freeze({waveform:'sample',sample:'accent',fundamentalHz:2382,duration:bank.samples.accent.frames/bank.sampleRate,gain:1}),
        rhythm: Object.freeze({waveform:'sample',sample:'tap',fundamentalHz:1080,duration:bank.samples.tap.frames/bank.sampleRate,gain:1})
    });
    function createBuffers(context) {
        return Object.fromEntries(Object.entries(bank.samples).map(([name,sample]) => {
            const bytes=atob(sample.pcm16),buffer=context.createBuffer(1,sample.frames,bank.sampleRate),channel=buffer.getChannelData(0);
            for(let index=0;index<sample.frames;index++) {
                const word=bytes.charCodeAt(index*2)|(bytes.charCodeAt(index*2+1)<<8);
                channel[index]=(word>=32768?word-65536:word)/32768;
            }
            return [name,buffer];
        }));
    }
    function play(context,buffers,name,when,gainLevel,output) {
        const source=context.createBufferSource(),gain=context.createGain();
        source.buffer=buffers[name];
        gain.gain.setValueAtTime(gainLevel,when);
        source.connect(gain);gain.connect(output);
        source.onended=()=>{source.disconnect();gain.disconnect();};
        source.start(when);
        return source;
    }
    function createOutput(context) {
        const output=context.createGain(),limiter=context.createDynamicsCompressor(),guard=context.createWaveShaper();
        output.gain.value=1;
        limiter.threshold.value=-1;limiter.knee.value=0;limiter.ratio.value=20;limiter.attack.value=.001;limiter.release.value=.08;
        // Web Audio compressors can overshoot on coincident short transients.
        // Leave each normalized single hit unchanged; guard only mixed peaks.
        const curve=new Float32Array(8193);
        for(let index=0;index<curve.length;index++) {
            const value=index*2/(curve.length-1)-1,magnitude=Math.abs(value);
            curve[index]=magnitude<=.95?value:Math.sign(value)*(.95+.03*Math.tanh((magnitude-.95)/.03));
        }
        guard.curve=curve;guard.oversample='none';
        output.connect(limiter);limiter.connect(guard);guard.connect(context.destination);
        return {output,limiter,guard};
    }
    return Object.freeze({profiles,createBuffers,createOutput,play,sampleRate:bank.sampleRate});
})();
""".replace("__BANK__", json.dumps(bank, separators=(",", ":")))
    TARGET.write_text(script, encoding="utf-8")
    print(json.dumps({"script": str(TARGET.relative_to(ROOT)), "bytes": len(script), "durationsMs": {name: round(sample["frames"] / SAMPLE_RATE * 1000, 1) for name, sample in samples.items()}}, indent=2))


if __name__ == "__main__":
    main()
